name: Laravel Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Namecheap Server
        run: |
          ssh -o StrictHostKeyChecking=no huzakdhg@huzaifarana.tech -p 21098 "
            cd public_html/techcommerce &&
            git pull origin main &&
            composer install --no-dev &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache
          "
